language: go

sudo: false

go:
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/etcd-io/etcd
  - cd $HOME/gopath/src/github.com/etcd-io/etcd
  - nohup go run main.go

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci